/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author José Henrique
 */
public class Fatorial extends javax.swing.JFrame {

    /**
     * Creates new form Fatorial
     */
    public Fatorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblcalc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldvalor = new javax.swing.JTextField();
        jButtoncalcular = new javax.swing.JButton();
        jLabelresultado = new javax.swing.JLabel();
        jTextFieldresultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        lblcalc.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Informe um número: ");
        lblcalc.add(jLabel1, new java.awt.GridBagConstraints());

        jTextFieldvalor.setColumns(5);
        lblcalc.add(jTextFieldvalor, new java.awt.GridBagConstraints());

        jButtoncalcular.setText("Cálcular");
        jButtoncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncalcularActionPerformed(evt);
            }
        });
        lblcalc.add(jButtoncalcular, new java.awt.GridBagConstraints());

        jLabelresultado.setText("O resultado é: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        lblcalc.add(jLabelresultado, gridBagConstraints);

        jTextFieldresultado.setEditable(false);
        jTextFieldresultado.setColumns(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        lblcalc.add(jTextFieldresultado, gridBagConstraints);

        getContentPane().add(lblcalc, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncalcularActionPerformed
        // TODO add your handling code here:
        boolean valid = true;
        if(jTextFieldvalor.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe um valor para cálcular!");
            valid = false;
            jTextFieldvalor.requestFocus();
            return;
        }
        if(valid){
        int i;
        int num = Integer.parseInt(jTextFieldvalor.getText());
        for (i = 1; num > 1; num = num - 1) {
            i = i * num;
        }
        jTextFieldresultado.setText(String.valueOf(i));
        }
    }//GEN-LAST:event_jButtoncalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fatorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //JFrame fatorial = new JFrame();
                //fatorial.setContentPane(new Fatorial());
                //fatorial.setExtendedState(JFrame.MAXIMIZED_BOTH);
                //fatorial.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
               // fatorial.pack();
                new Fatorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoncalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelresultado;
    private javax.swing.JTextField jTextFieldresultado;
    private javax.swing.JTextField jTextFieldvalor;
    private javax.swing.JPanel lblcalc;
    // End of variables declaration//GEN-END:variables
}
